import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: NextRequest) {
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return new Response("Unauthorized", { status: 401 });
  }

  const supabase = createClient();
  if (!supabase) {
    return NextResponse.json({ error: "supabase_not_configured" }, { status: 500 });
  }

  // Get recent opportunities added in last 24 hours
  const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { data: recentOpps } = await supabase
    .from("opportunities")
    .select("title, province, category, issuing_entity, closing_date")
    .gte("created_at", since)
    .order("created_at", { ascending: false })
    .limit(10);

  if (!recentOpps || recentOpps.length === 0) {
    return NextResponse.json({ ok: true, message: "No new opportunities to report" });
  }

  // Build summary post
  const today = new Date().toISOString().split("T")[0];
  const slug = `daily-brief-${today}`;

  // Check if today's brief already exists
  const { data: existing } = await supabase
    .from("content_posts")
    .select("id")
    .eq("slug", slug)
    .maybeSingle();

  if (existing) {
    return NextResponse.json({ ok: true, message: "Today's brief already published" });
  }

  // Group by province
  const byProvince: Record<string, typeof recentOpps> = {};
  for (const opp of recentOpps) {
    const prov = opp.province || "National";
    if (!byProvince[prov]) byProvince[prov] = [];
    byProvince[prov].push(opp);
  }

  // Build markdown body
  const lines: string[] = [
    `## ${recentOpps.length} new opportunities indexed today`,
    "",
    `*${new Date().toLocaleDateString("en-CA", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}*`,
    "",
  ];

  for (const [province, opps] of Object.entries(byProvince)) {
    lines.push(`### ${province}`);
    for (const opp of opps) {
      lines.push(`- **${opp.title}** — ${opp.issuing_entity ?? "Government"}`);
      if (opp.closing_date) {
        lines.push(`  Closes: ${opp.closing_date}`);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*This brief is auto-generated by the Surplus Bus intelligence engine.*");

  const body_md = lines.join("\n");

  const { error } = await supabase.from("content_posts").insert({
    title: `Daily Intelligence Brief — ${today}`,
    slug,
    summary: `${recentOpps.length} new public-sector opportunities indexed across ${Object.keys(byProvince).length} province(s).`,
    body_md,
    status: "published",
    authored_by_agent: true,
    published_at: new Date().toISOString(),
  });

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    post_slug: slug,
    opportunities_covered: recentOpps.length,
  });
}
